In [1]:
import numpy as np
np.__version__

'1.23.3'

In [13]:
np.linspace(start=1, stop=30, num=30).reshape((3,5,2))

array([[[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]],

       [[11., 12.],
        [13., 14.],
        [15., 16.],
        [17., 18.],
        [19., 20.]],

       [[21., 22.],
        [23., 24.],
        [25., 26.],
        [27., 28.],
        [29., 30.]]])

In [14]:
a = np.array([
    [5,1,2],
    [6,3,8],
    [4,7,9]
])

print(a, a.shape , a.ndim)

[[5 1 2]
 [6 3 8]
 [4 7 9]] (3, 3) 2
